APT::FTPArchive::Release::Origin "omnihear";
APT::FTPArchive::Release::Label "omnihear";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "omnihear APT repository";
